{"name": "test_login_alert[case1]", "status": "passed", "description": "异常用例，错误信息弹窗提示", "attachments": [{"name": "log", "source": "75578a86-db33-4253-b159-6ba82767b7db-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '18684720553', 'pwd': 'python888', 'expected': '帐号或密码错误!'}"}], "start": 1590503410801, "stop": 1590503411929, "uuid": "2aa16507-e6b1-4c9d-8146-ed9387da3365", "historyId": "65ff18146948f2658303e7b68ac96de1", "testCaseId": "8b653efc132135221fc57baf686031ef", "fullName": "testcases.test_login.TestLogin#test_login_alert", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "7072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}