{"name": "test_login_alert[case1]", "status": "passed", "description": "异常用例，错误信息弹窗提示", "attachments": [{"name": "log", "source": "f41d500a-77ae-48c0-8e5a-b5ea35aedaeb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '18684720553', 'pwd': 'python888', 'expected': '帐号或密码错误!'}"}], "start": 1590498341545, "stop": 1590498342850, "uuid": "b80e315b-3980-4c39-bf73-16b97dccfc6a", "historyId": "65ff18146948f2658303e7b68ac96de1", "testCaseId": "8b653efc132135221fc57baf686031ef", "fullName": "testcases.test_login.TestLogin#test_login_alert", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "8788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}