{"name": "test_login_alert[case1]", "status": "passed", "description": "异常用例，错误信息弹窗提示", "attachments": [{"name": "log", "source": "6c66f8cd-307f-4ec1-8494-dc60d6d25277-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '18684720553', 'pwd': 'python888', 'expected': '帐号或密码错误!'}"}], "start": 1590758318636, "stop": 1590758319791, "uuid": "d426b909-97b4-4fab-801b-2aaea122d72a", "historyId": "65ff18146948f2658303e7b68ac96de1", "testCaseId": "8b653efc132135221fc57baf686031ef", "fullName": "testcases.test_login.TestLogin#test_login_alert", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}